/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2BgU5ut84W0
 */
import { TabsTrigger, TabsList, TabsContent, TabsRoot } from "./ui/tabs"

export function Tabs() {
  return (
    <div key="1" className="flex flex-col h-screen bg-gray-900">
      <header className="flex items-center justify-between px-6 py-4 bg-gray-700 text-white shadow-md">
        <h1 className="text-3xl font-bold">耀州窑</h1>
        <p className="text-sm italic">中国古代陶瓷烧制技术的瑰宝</p>
      </header>
      <TabsRoot className="w-full" defaultValue="history">
        <TabsList className="w-full flex justify-around border-b border-gray-600 bg-gray-800 text-gray-300">
          <TabsTrigger className="py-2 px-4 text-lg font-semibold" value="history">
            历史介绍
          </TabsTrigger>
          <TabsTrigger className="py-2 px-4 text-lg font-semibold" value="features">
            工艺特点
          </TabsTrigger>
          <TabsTrigger className="py-2 px-4 text-lg font-semibold" value="exhibits">
            展品展示
          </TabsTrigger>
        </TabsList>
        <TabsContent className="flex-1 overflow-auto p-6 bg-gray-800 text-gray-300 shadow-inner" value="history">
          <h2 className="text-2xl font-bold mb-4 text-gray-200">耀州窑历史</h2>
          <p className="mb-4 text-gray-400">耀州窑是中国古代陶瓷烧制技术的瑰宝，历史悠久，工艺精湛。</p>
          <img
            alt="历史图片"
            className="w-full h-[200px] object-cover rounded-md shadow-lg"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
        </TabsContent>
        <TabsContent className="flex-1 overflow-auto p-6 bg-gray-800 text-gray-300 shadow-inner" value="features">
          <h2 className="text-2xl font-bold mb-4 text-gray-200">耀州窑工艺特点</h2>
          <p className="mb-4 text-gray-400">耀州窑的陶瓷工艺有其独特的特点，包括...</p>
          <img
            alt="工艺特点图片"
            className="w-full h-[200px] object-cover rounded-md shadow-lg"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
        </TabsContent>
        <TabsContent className="flex-1 overflow-auto p-6 bg-gray-800 text-gray-300 shadow-inner" value="exhibits">
          <h2 className="text-2xl font-bold mb-4 text-gray-200">耀州窑展品展示</h2>
          <p className="mb-4 text-gray-400">以下是一些耀州窑的代表性展品...</p>
          <img
            alt="展品图片"
            className="w-full h-[200px] object-cover rounded-md shadow-lg"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
        </TabsContent>
      </TabsRoot>
    </div>
  )
}
